# Generated by Django 5.0.3 on 2024-03-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foottraffic',
            name='city',
            field=models.CharField(db_index=True, help_text='The city where the shopping center is located', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foottraffic',
            name='formatted_address',
            field=models.CharField(db_index=True, help_text='The full address of the shopping center', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foottraffic',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of the shopping center', max_length=255),
        ),
        migrations.AlterField(
            model_name='foottraffic',
            name='state',
            field=models.CharField(db_index=True, help_text='The state code where the shopping center is located', max_length=2, null=True),
        ),
    ]
